version: "3"
services:
  react_news_app:
    container_name: react_news_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/app
    command: yarn dev
